version: '3.8'

services:
  ollama:
    build:
      context: ./ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./data/chroma:/data/chroma
    networks:
      - rag_network

  chromadb:
    build:
      context: ./chromadb
    container_name: chromadb
    ports:
      - "8000:8000"
    environment:
      ALLOW_RESET: "TRUE"
    depends_on:
      - ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://host.docker.internal:8000/api/v1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/ollama:/data/ollama
    networks:
      - rag_network

  rag_service:
    build:
      context: ./rag_service
    container_name: rag_service
    depends_on:
      chromadb:
        condition: service_healthy
    environment:
      ALLOW_RESET: "TRUE"
    command: python ./rag_query.py
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge
